config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'about' => 'home#about', as: :about

	devise_for :skaters, controllers: {
		registrations: 'skaters/registrations',
		sessions: 'skaters/sessions',
    passwords: 'skaters/passwords'
	}

  resources :skaters, param: :name, only: [:show, :edit, :update, :index] do
  	get 'following' => 'relationships#index',as: :followings
  end

  get 'skaters/:name/delete' => 'skaters#withdraw', as: :delete_account
  resources :posts, param: :title do
  	resources :comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :parks, param: :name, constraints: { name: /[^\/]+/ }
  resources :countries, param: :name

  post 'follow/:name' => 'relationships#create', as: :follow
  delete 'unfollow/:name' => 'relationships#destroy', as: :unfollow

	devise_for :admins, skip: :all
	devise_scope :admin do
		get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
		post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
		delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
	end

  namespace :admin do
    resources :skaters, param: :id, only: [:index, :edit, :update]
    resources :parks, param: :id, only: [:edit, :update, :destroy, :index]
    resources :posts, param: :id, only: [:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :countries, param: :id, only: [:index, :edit, :update, :destroy]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skater.rb
class Skater < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :parks
  has_many :countries
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :skater

  def follow(skater)
    unless self == skater
      self.relationships.find_or_create_by(follow_id: skater.id)
    end
  end

  def unfollow(skater)
    relationship = self.relationships.find_by(follow_id: skater.id)
    relationship.destroy if relationship
  end

  def following?(skater)
    self.followings.include?(skater)
  end

  validates :name, presence: true, uniqueness: true
  validates :is_deleted, inclusion: { in: [true, false]}, defalut: false


  attachment :profile_image

  scope :search, -> (search_params) do
    return if search_params.blank?
    name_like(search_params[:name])
  end
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }

  def to_param
    return self.name
    if admin_signed_in?
      return self.id
    end
  end

  def active_for_authentication?
    super && ( self.is_deleted == false)
  end
end

app/controllers/admin/skaters_controller.rb
class Admin::SkatersController < ApplicationController
	before_action :authenticate_admin!

  def index
  	@skaters = Skater.page(params[:page]).per(10).reverse_order
  end

  def edit
  	@skater = Skater.find(params[:id])
  end

  def update
  	@skater = Skater.find(params[:id])
  	if @skater.update(skater_params)
      if @skater.is_deleted == true
        followings = Relationship.where(skater_id: @skater.id)
        followings.destroy_all if followings
        followers = Relationship.where(follow_id: @skater.id)
        followers.destroy_all if followers
        @skater.comments.destroy_all
        @skater.favorites.destroy_all
      end
  		flash[:notice]= "スケーター情報を変更しました"
  		redirect_to admin_skaters_path
  	else
  		render :edit
  	end
  end

  private
  def skater_params
  	params.require(:skater).permit(:name, :biography, :profile_image, :remove_profile_image, :is_deleted)
  end
end

app/controllers/skaters/passwords_controller.rb
# frozen_string_literal: true

class Skaters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/skaters/registrations_controller.rb
# frozen_string_literal: true

class Skaters::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_params, only: [:create, :update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_account_update_params
  #  devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  #  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  #end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    flash[:notice]="アカウント作成成功"
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #  super(resource)
  # end
end

app/controllers/skaters/sessions_controller.rb
# frozen_string_literal: true

class Skaters::SessionsController < Devise::SessionsController
  before_action :reject_skater, only: [:create]
  #before_action :configure_permitted_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  def after_sign_in_path_for(resource)
    flash[:notice]="ログイン成功"
    root_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_skater
    @skater = Skater.find_by(email: params[:skater][:email].downcase)
    if @skater
      if (@skater.valid_password?(params[:skater][:password])&& (@skater.active_for_authentication? == false))
        flash[:notice]= "退会済みです。新しくアカウントを作り直すか、お問い合わせフォームから連絡ください。"
        redirect_to new_skater_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_permitted_params
  #  devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
  #end
end

app/controllers/skaters_controller.rb
class SkatersController < ApplicationController
  before_action :authenticate_skater!, except: [:index]
  before_action :skater_is_deleted
  before_action :set_current_skater, only: [:edit, :update, :withdraw]

  def show
    @skater = Skater.find_by(name: params[:name])
  	@posts = @skater.posts.page(params[:page]).reverse_order
    if @skater.is_deleted == true
      flash[:notice]="退会済みアカウントの詳細はご覧になれません"
      redirect_to skaters_path
    end
  end

  def index
    @skaters = Skater.where(is_deleted: false).page(params[:page]).reverse_order
    @search_params = skater_search_params
    if params[:search]
      @skaters = Skater.search(@search_params).page(params[:page]).reverse_order
    end
  end

  def edit
  end

  def update
    if params[:remove_profile_image]
      image = @skater.profile_image
      image.destroy
    end
    if @skater.update(skater_params)
      flash[:notice]= "プロフィールを更新しました"
      redirect_to skater_path(@skater)
    else
      render :edit
    end
  end

  def withdraw
    @skater.update(is_deleted: true)
    reset_session
    followings = Relationship.where(skater_id: @skater.id)
    followings.destroy_all if followings
    followers = Relationship.where(follow_id: @skater.id)
    followers.destroy_all if followers
    @skater.comments.destroy_all
    @skater.favorites.destroy_all
    flash[:notice] ="アカウントを削除しました"
    redirect_to root_path
  end

  private
  def skater_params
    params.require(:skater).permit(:name, :biography, :profile_image, :remove_profile_image)
  end

  def skater_search_params
    params.fetch(:search, {}).permit(:name)
  end

  def set_current_skater
    @skater = current_skater
  end

end

app/helpers/admin/skaters_helper.rb
module Admin::SkatersHelper
end

app/helpers/skaters_helper.rb
module SkatersHelper
end

app/views/admin/skaters/edit.html.erb
<div class="container pt-5" style="height: auto;">
	<div class="form-header">
		<h4 class="form-header-title text-left"><%= @skater.name %>のアカウント</h4>
	</div>
	<div class="row justify-content-center">
		<div class="form-horizontal col-9">
			<%= form_with model: @skater, url: admin_skater_path, method: :patch, local: true do |f| %>
				<%= render "layouts/error_messages", hoge: @skater %>

				<div class="form-group">
					<%= f.label :profile_image%>
					<%= f.attachment_field :profile_image %>
				</div>

				<div class="form-group">
					<% if @skater.profile_image.present? %>
					<p> 削除する場合はチェックしてください</p>
						<%= f.check_box :remove_profile_image %>
						<%= attachment_image_tag @skater, :profile_image, size: "100x100" %>
					<% end %>
				</div>

				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class:"form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :biography %>
					<%= f.text_area :biography, class:"form-control", rows:'10' %>
				</div>

				<div class="form-group">
					<label for="is_deleted">アカウント状態</label>
					<%= f.select :is_deleted, [["既存", false], ["削除", true]],:prompt => false %>
				</div>

				<div class="actions">
					<%= f.submit "アカウント編集", class:"btn btn-info col-3 float-right" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/skaters/index.html.erb
<div class="container pt-5" style="height: auto;">
	<p class="notice"><%= notice %></p>
	<div class="row mt-0">
		<div class="page-header title col-12">
			<h4>アカウント一覧</h4>
		</div>
	</div>

	<div class="row justify-content-center">

		<div class="page-content col-12 mt-2">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>id</th>
						<th>アバター</th>
						<th>アカウント名</th>
						<th>メールアドレス</th>
						<th>BIOGRAPHY</th>
						<th>投稿数</th>
						<th>退会フラグ</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @skaters.each do |skater| %>
						<tr>
							<td><%= skater.id %></td>
							<td><%= attachment_image_tag skater, :profile_image, class:"img-fluid rounded-circle", size: '100x100', fallback: "no_image.svg" %>
							</td>
							<td><%= skater.name %></td>
							<td><%= skater.email %></td>
							<td><%= skater.biography %></td>
							<td>
								<%= link_to skater.posts.count, admin_posts_path(skater_id: skater.id) %>
							</td>
							<td>
								<% if skater.is_deleted == true %>削除済み
								<% else %> exists
								<% end %>
							</td>
							<td>
								<%= link_to '編集', edit_admin_skater_path(skater.id) %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<%= paginate @skaters %>
		</div>
	</div>
</div>