config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'about' => 'home#about', as: :about

	devise_for :skaters, controllers: {
		registrations: 'skaters/registrations',
		sessions: 'skaters/sessions',
    passwords: 'skaters/passwords'
	}

  resources :skaters, param: :name, only: [:show, :edit, :update, :index] do
  	get 'following' => 'relationships#index',as: :followings
  end

  get 'skaters/:name/delete' => 'skaters#withdraw', as: :delete_account
  resources :posts, param: :title do
  	resources :comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :parks, param: :name, constraints: { name: /[^\/]+/ }
  resources :countries, param: :name

  post 'follow/:name' => 'relationships#create', as: :follow
  delete 'unfollow/:name' => 'relationships#destroy', as: :unfollow

	devise_for :admins, skip: :all
	devise_scope :admin do
		get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
		post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
		delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
	end

  namespace :admin do
    resources :skaters, param: :id, only: [:index, :edit, :update]
    resources :parks, param: :id, only: [:edit, :update, :destroy, :index]
    resources :posts, param: :id, only: [:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :countries, param: :id, only: [:index, :edit, :update, :destroy]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :parks
	accepts_nested_attributes_for :parks

	scope :search, -> (search_params) do
		return if search_params.blank?
		name_like(search_params[:name])
	end
	scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }

	validates :name, presence: true, uniqueness: true

	def to_param
    	return self.name
    	if admin_signed_in?
    		return self.id
    	end
  	end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
	before_action :authenticate_admin!

  def index
  	@countries = Country.all
  end

  def edit
  	@country = Country.find(params[:id])
  end

  def update
  	@country = Country.find(params[:id])
  	if @country.update(country_params)
  		flash[:notice]="国情報を変更しました"
  		redirect_to admin_countries_path
  	else
  		render :edit
  	end
  end

  def destroy
  	country = Country.find(params[:id])
  	country.destroy
  	redirect_to admin_countries_path
  end

  private
  def country_params
  	params.require(:country).permit(:name, :description)
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :authenticate_skater!, except: [:index, :show]
  before_action :skater_is_deleted
	before_action :set_country, only: [:edit, :update, :show, :destroy]

  def new
  	@country = Country.new
  end

  def create
  	@country = Country.new(country_params)
  	if @country.save
  		flash[:notice]= "新しく国情報を保存しました"
  		redirect_to countries_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @country.update(country_params)
  		redirect_to country_path(@country)
  	else
  		render :edit
  	end
  end

  def show
  	@parks = @country.parks.page(params[:page]).reverse_order
  end

  def index
  	@countries = Country.page(params[:page]).reverse_order
  	@search_params = country_search_params
  	@countries = Country.search(@search_params).page(params[:page]).reverse_order
  end

  def destroy
  	@country.destroy
  	redirect_to countries_path
  end

  private
  def country_params
  	params.require(:country).permit(:name, :description)
  end

  def country_search_params
  	params.fetch(:search, {}).permit(:name)
  end

  def set_country
  	@country = Country.find_by(name: params[:name])
  end
end

app/helpers/admin/countries_helper.rb
module Admin::CountriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/admin/countries/edit.html.erb
<div class="container pt-5" style="height: auto;">
	<div class="row mt-0">
		<div class="form-header">
			<h4 class="form-header-title text-left"><%= @country.name %>情報編集</h4>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="form col-10">
			<%= form_for(@country, url: admin_country_path(@country.id), method: :patch) do |f| %>
				<%= render "layouts/error_messages", hoge: @country %>
				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class:"form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :description %>
					<%= f.text_area :description, rows:'10', class:"form-control" %>
				</div>
				<div class="actions">
					<%= f.submit "Submit", class:"btn btn-outline-info" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/countries/index.html.erb
<div class="container pt-5" style="height: auto;">
	<p class="notice"><%= notice %></p>
	<div class="row mt-0">
		<h3 class="page-header">国一覧</h3>
	</div>
	<div class="row">
		<div class="col-4">
			<div class="list-group" id="list-tab" role="tablist">
				<% @countries.each do |country| %>
				<a class="list-group-item list-group-item-action" id="list-<%= country.name %>-list" data-toggle="list" href="#<%= country.name %>" role="tab" aria-controls="<%= country.name %>"><%= country.name %></a>
				<% end %>
			</div>
		</div>
		<div class="col-8">
			<div class="tab-content" id="nav-tabContent">
				<% @countries.each do |country| %>
				<div class="tab-pane fade" id="<%= country.name %>" role="tabpanel" aria-labelledby="list-<%= country.name %>-list">
				<div class="col-12"><%= country.description %></div>
					<div class="col-12 mt-4">パーク数：  <%= link_to country.parks.count, admin_parks_path(country_id: country.id) %>
					</div>
					<div class="col-12 text-right mt-4"><%= link_to 'Edit',edit_admin_country_path(country.id), class:"btn btn-outline-info btn-sm mr-4" %><%= link_to ' Delete', admin_country_path(country.id), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-sm btn-outline-danger" %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>