config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'about' => 'home#about', as: :about

	devise_for :skaters, controllers: {
		registrations: 'skaters/registrations',
		sessions: 'skaters/sessions',
    passwords: 'skaters/passwords'
	}

  resources :skaters, param: :name, only: [:show, :edit, :update, :index] do
  	get 'following' => 'relationships#index',as: :followings
  end

  get 'skaters/:name/delete' => 'skaters#withdraw', as: :delete_account
  resources :posts, param: :title do
  	resources :comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :parks, param: :name, constraints: { name: /[^\/]+/ }
  resources :countries, param: :name

  post 'follow/:name' => 'relationships#create', as: :follow
  delete 'unfollow/:name' => 'relationships#destroy', as: :unfollow

	devise_for :admins, skip: :all
	devise_scope :admin do
		get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
		post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
		delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
	end

  namespace :admin do
    resources :skaters, param: :id, only: [:index, :edit, :update]
    resources :parks, param: :id, only: [:edit, :update, :destroy, :index]
    resources :posts, param: :id, only: [:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :countries, param: :id, only: [:index, :edit, :update, :destroy]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :skater
	belongs_to :park, optional: true
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

	has_one_attached :video

	validates :title, presence: true, uniqueness: true
	validates :skater_id, presence: true

	def favorited_by?(skater)
    	favorites.where(skater_id: skater.id).exists?
  	end


  	def to_param
    	return self.title
    	if admin_signed_in?
    		return self.id
    	end
  	end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :authenticate_admin!

  def index
  	if params[:skater_id]
  		@posts = Post.where(skater_id: params[:skater_id]).page(params[:page]).per(12).reverse_order
  	else
      @posts = Post.page(params[:page]).per(10).reverse_order
    end
  end

  def destroy
  	post = Post.find(params[:id])
  	if post.destroy
  		flash[:notice]="投稿を削除しました"
  		redirect_to admin_posts_path
  	else
  		@posts = Post.page(params[:page]).per(12).reverse_order
  		render :index
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_skater!, except: [:index]
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.page(params[:page]).reverse_order
	end

	def show
		skater = Skater.find_by(id: @post.skater_id)
		@posts = skater.posts.page(params[:page]).reverse_order
		@comment = Comment.new
		@comments = @post.comments
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.skater_id = current_skater.id
		if params[:park_id].present?
			@post.park_id = params[:park_id]
		end
		if @post.save
			flash[:notice] = "投稿成功しました"
			redirect_to post_path(@post.title)
		else
			@parks = Park.all
			render :new
		end
	end

	def edit
	end

	def update
		@post.park_id = params[:park_id]
		if @post.update(post_params)
			flash[:notice]= "動画を編集しました"
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		flash[:notice]= "投稿を削除しました"
		redirect_to posts_path
	end

	private
	def set_post
		@post = Post.find_by(title: params[:title])
	end
	def post_params
		params.require(:post).permit(:title, :caption, :video, :park_id)
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form-horizontal col-10">
	<%= form_with model: post, local: true do |f| %>
		<%= render "layouts/error_messages", hoge: post %>

		<div class="form-group">
			<%= f.label :video, for:"upload-video" %>
			<%= f.file_field :video, id:"upload-video" %>
		</div>

		<div class="video-preview"></div>

		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :caption %>
			<%= f.text_area :caption, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :park_id %>
			<%= f.collection_select :park_id, Park.all, :id, :name, include_blank: true, class:"form-control" %>
		</div>
		<div class="actions">
			<%= f.submit "Send", class:"btn btn-info col-3 float-right" %>
		</div>
	<% end %>
</div>

app/views/posts/_videos.html.erb
<div class="video-box">
	<% posts.each do |post| %>
		<% if post.skater.is_deleted == true %>
		<% else %>
		<div class="post col-3 mt-3">
			<div class="embed-responsive embed-responsive-16by9">
			    <%= video_tag rails_blob_path(post.video, disposition: "attachment"), :controls => true, class:"embed-responsive-item" %>
			</div>
			<div class="row m-0">
				<div class="col-2 p-0">
					<%= link_to skater_path(post.skater) do %>
				    <%= attachment_image_tag post.skater, :profile_image, class:"img-fluid rounded-circle", alt: "Responsive image", fallback: "no_image.svg" %>
					<% end %>
				</div>
				<div class="post col-7 clearfix">
					<span class="d-inline-block text-truncate float-left"><%= link_to post_path(post) do %><%= post.title %><% end %><br><%= post.skater.name %></span>
				</div>

				<div class="col-3 float-right p-0 m-0">
					<span><i class="far fa-comments"></i><%= post.comments.count %></span>
					<% if skater_signed_in? %>
						<% if post.favorited_by?(current_skater) %>
				    		<span><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i><%= post.favorites.count %></span>
						<% else %>
					   		<span><i class="fa fa-heart-o" aria-hidden="true"></i><%= post.favorites.count %></span>
						<% end %>
					<% else %>
						<span><i class="fa fa-heart-o" aria-hidden="true"></i><%= post.favorites.count %></span>
					<% end %><br />
				</div>
			</div>
		</div>
		<% end %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<div class="container pt-5" style="height: auto;">
	<div class="form-header mt-0">
		<h3 class="form-header-title text-left">投稿編集画面</h3><%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger col-3 float-right" %>
	</div>
	<div class="row justify-content-center">

		<%= render "form", post: @post %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container pt-3" style="height: auto;">
	<div class="row justify-content-center mt-0">
		<div class="col-12 text-left"><h3>VIDEOS</h3></div>
		<div id="videos" class="col-12">
			<%= render partial: 'posts/videos', locals: {posts: @posts} %>
		</div>
		<% unless @posts.count < 5 %>
			<div class="page-load-status">
				<div class="infinite-scroll-request">
					loading... <br>
				<%= paginate @posts %>
				</div>
				<p class="infinite-scroll-last">
					end of contents
				</p>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container pt-5" style="height: auto;">
	<div class="form-header mt-0">
		<h3 class="form-header-title text-left">新規投稿作成</h3>
	</div>
	<div class="row justify-content-center">
		<%= render "form", post: @post %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container pt-5" style="height: auto;">
	<p class="notice"><%= notice %></p>
	<div class="row justify-content-center mt-0">
		<div class="col-8">
			<div class="embed-responsive embed-responsive-16by9">
				<% if @post.video.attached? %>
					<%= video_tag rails_blob_path(@post.video, disposition: "attachment"), :controls => true, class:"embed-responsive-item" %>
				<% end %>
			</div>
			<div class="row mt-3">
				<div class="col-2">
					<%= link_to skater_path(@post.skater) do %>
				    	<%= attachment_image_tag @post.skater, :profile_image, class:"img-fluid rounded-circle", alt: "Responsive image", fallback: "no_image.svg" %>
					<% end %>
				</div>
				<div class="col-10 clearfix m-auto">
					<h4 class="float-left"><%= @post.title %><br/>
						<small><%= @post.skater.name %></small></h4>

						<div id="favorite_buttons_<%= @post.title %>" class="float-right">
							<%= render partial: 'favorites/favorite', locals: {post: @post} %>
						</div>
				</div>
				<% if @post.park_id.present? %>
					<p class="col-12 text-right">@ <%= link_to park_path(@post.park), class:"park-link" do %><%= @post.park.name %><% end %></p>
				<% end %>

			</div>
			<div class="row overflow-auto ml-2 clearfix">
				<p class="lead col-12 float-left"><%= simple_format(@post.caption) %></p>
			</div>
		</div>
		<div class="comments col-md-4 col-12">
			<h5>コメント</h5>
			<div class="form-horizontal clearfix">
				<%= form_for [@post, @comment] do |f| %>
	  				<div class="form-group">
	      				<%= f.text_area :comment, rows:'3', class:"form-control pb-0", placeholder:"コメント入力" %>
	  				</div>
	  				<div class="actions">
	  					<%= f.button :type => "submit", class:"btn btn-outline-info btn-sm float-right mt-0" do %><i class="far fa-paper-plane"></i><% end %>
	  				</div>
				<% end %>
			</div>

			<% if @comments.blank? %>
				<p>コメントはありません</p>
			<% end %>

			<div class="comments-content overflow-auto mt-1">
				<% @comments.each do |comment| %>
					<div class="row m-0 mt-2">
						<div class="col-2 pl-0">
							<%= link_to skater_path(comment.skater) do %>
			    				<%= attachment_image_tag comment.skater, :profile_image, class:"profile-image img-fluid rounded-circle", alt: "Responsive image", fallback: "no_image.svg" %>
			    			<% end %>
			    		</div>

			    		<div class="post col-10 pr-0 clearfix">
			    			<span class="text-body float-right">by <%= comment.skater.name %></span>
			    		</div>
						<div class="col-12 pr-0 clearfix">
							<span class="text-body"><%= simple_format(comment.comment) %></span>

							<% if comment.skater == current_skater %>
								<%= link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-outline-danger btn-sm float-right mt-0" %>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>

	<div class="row justify-content-center">
		<div class="index col-12 text-left"><h5><%= @post.skater.name %>さんの動画</h5></div>
		<div id="videos" class="col-12">
			<%= render partial: 'posts/videos', locals: {posts: @posts} %>
		</div>
		<% unless @posts.count < 5 %>
			<div class="page-load-status">
				<div class="infinite-scroll-request">
					loading... <br>
					<%= paginate @posts %>
				</div>
				<p class="infinite-scroll-last">
					end of contents
				</p>
			</div>
		<% end %>
	</div>

</div>