config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get 'about' => 'home#about', as: :about

	devise_for :skaters, controllers: {
		registrations: 'skaters/registrations',
		sessions: 'skaters/sessions',
    passwords: 'skaters/passwords'
	}

  resources :skaters, param: :name, only: [:show, :edit, :update, :index] do
  	get 'following' => 'relationships#index',as: :followings
  end

  get 'skaters/:name/delete' => 'skaters#withdraw', as: :delete_account
  resources :posts, param: :title do
  	resources :comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :parks, param: :name, constraints: { name: /[^\/]+/ }
  resources :countries, param: :name

  post 'follow/:name' => 'relationships#create', as: :follow
  delete 'unfollow/:name' => 'relationships#destroy', as: :unfollow

	devise_for :admins, skip: :all
	devise_scope :admin do
		get 'admin/sign_in' => 'admin/sessions#new', as: :new_admin_session
		post 'admin/sign_in' => 'admin/sessions#create', as: :admin_session
		delete 'admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
	end

  namespace :admin do
    resources :skaters, param: :id, only: [:index, :edit, :update]
    resources :parks, param: :id, only: [:edit, :update, :destroy, :index]
    resources :posts, param: :id, only: [:index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :countries, param: :id, only: [:index, :edit, :update, :destroy]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>